# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['25.2.3']
        elixir: ['1.14.4']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.15.4
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ hashFiles('**/mix.lock') }}-${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}
        restore-keys:
          - ${{ hashFiles('**/mix.lock') }}-${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}
          - ${{ hashFiles('**/mix.lock') }}-${{ runner.os }}-mix
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test --cover
